### ISSUE TITLE
What If Mode Not Working

### ISSUE THREAD

**Issue by myalexbennett** [jslater89/uspsa-result-viewer#16]
What If mode doesn't seem to work on Windows Chrome.

Steps to reproduce:
1. Click the "What If" link
2.  Nothing Happens...

**Comment by jslater89** [comment]
Couldn't reproduce an issue.

If you hit the what-if link, you should be in what-if mode, at which point you can select a stage and edit shooters' scores for that stage by clicking their name. At that point, their names should show up in red to indicate that they've been edited. It could probably stand to be documented better, although I'm not quite sure where to put the instructions.

Let me know if that solves things.
