### ISSUE TITLE
CORS error on flutter web

### ISSUE THREAD

**Issue by usseiin** [jslater89/uspsa-result-viewer#56]
I encountered an issue while attempting to upload the "report.txt" file from a PractiScore URL on Flutter web, although it functions correctly on mobile devices. The error message I received was a "403 Forbidden" error, stating that the origin "http://localhost:33933" was not authorized by the proxy operator.

Interestingly, I observed that this functionality works seamlessly on a GitHub page (specifically, https://jslater89.github.io/uspsa-result-viewer/#/), where it is hosted. I'm curious about how this was achieved.

**Comment by jslater89** [comment]
The web app uses a CORS Anywhere proxy to make the request necessary to download reports from PractiScore. For the github-hosted version, I run a proxy on one of my servers that only accepts requests from the jslater89.github.io origin.

Look for getProxyUrl in the source code to substitute your own proxy.

That said, I'm probably going to be sunsetting the web app version with the upcoming release—PractiScore is evidently blocking the server where that proxy is hosted now.
